### ISSUE TITLE
Disable only the rule about "not_that_char.non_ascii_char"

### ISSUE THREAD

**Issue by david-maison** [OCamlPro/typerex-lint#151]
Tested on tag `alpha.0.1` (commit aa0e597)

In one of our projects, we can find some non-ascii characters in comments but I still want to check about tabs (even if it can be detected easily with grep).

Is it possible to disable the sub-rule `non_ascii_char` but to let enabled the sub-rule `tab_for_indent` (and more generally only a/several sub-rules like this)?

**Comment by Michaaell** [comment]
You can use the option "warnings" of the plugin to do just that.
This uses the same syntax as -w of ocamlc.
In your example :
--plugin-text.not-that-char.warnings +A-2
or in the config file :
...
not_that_char = {
    ...
    warnings = "+A-2"
}
...

**Comment by david-maison** [comment]
Indeed, this solves the problem. Thanks!
