### ISSUE TITLE
ocp-lint does not print any warning anymore

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/typerex-lint#50]
With current master:
./_obuild/ocp-lint/ocp-lint.asm --path . --disable-plugin_sempatch --disable-plugin_core --disable-plugin_core.code_length

keeps displaying warnings that should not be printed (in particular, both plugins are disabled...).

**Comment by OCamlPro-Bozman** [comment]
By default all plugins and linters are disable. That's why nothing is printed. Maybe we should remove .ocplint in the repository and let user save his own configuration file.
