### ISSUE TITLE
ocp-lint-minimal is not minimal

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/typerex-lint#57]
ocp-lint-minimal should contain no plugin

**Comment by lefessan** [comment]
See other comments on https://github.com/OCamlPro/typerex-lint/pull/56

**Comment by OCamlPro-Bozman** [comment]
ocp-lint-minimal does not contain plugins anymore, can you tell me if not ?

**Comment by lefessan** [comment]
ok
