### ISSUE TITLE
`ocp-lint --init` should also create a `.ocplint` if it does not exist

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/typerex-lint#59]

**Comment by OCamlPro-Bozman** [comment]
Actually you have option `--save-config` to save .ocplint default configuration. But we can generate it when we initialize the database.

**Comment by OCamlPro-Bozman** [comment]
FIx in [004f8c0](https://github.com/OCamlPro/typerex-lint/pull/61/commits/004f8c003908532bef7af1f0d6e14d6b643348f4).
